USE `dbTest`;
DROP TABLE IF EXISTS `CurricularCycle`;
DELIMITER //
CREATE TABLE IF NOT EXISTS `CurricularCycle` (
	`id` TINYINT(1) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	-- `CurricularGrade` TINYINT(1) NOT NULL,
	-- `level` CHAR(2) CHARACTER SET ascii NOT NULL,
	`notation` CHAR(4) CHARACTER SET ascii NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
//
DELIMITER ;